.PHONY: clean All

All:
	@echo "----------Building project:[ campelmag - Debug ]----------"
	@cd "campelmag" && "$(MAKE)" -f  "campelmag.mk"
clean:
	@echo "----------Cleaning project:[ campelmag - Debug ]----------"
	@cd "campelmag" && "$(MAKE)" -f  "campelmag.mk" clean
